    #include<bits/stdc++.h>
    using namespace std;
    int main()
    {
        ios_base::sync_with_stdio(false);
        int t,n,x,a[100005],b,c=0,d=0,e,f,g,h,i,j=0,k,l;
        cin>>t;
        for(l=0;l<t;l++)
        {
            cin>>n>>x;
            for(i=1;i<=n;i++)
            {
                cin>>a[i];
                if(a[i]>=x)
                {
                    d++;
                }
            }
            sort(a+1,a+1+n);
            for(i=1;i<=n-d;i++)
            {
                e=a[i]*2;
                if(e>=x)
                {
                    c++;
                }
            }
            f=c/2;
            if(c%2!=0)
            {
                c=c-1;
            }
            g=n-(c+d);
            b=g;
            for(i=1;i<=g;i++)
            {
                if(x%a[i]==0)
                {
                    k=x/a[i];
                }
                else{
                    k=(x/a[i])+1;
                }
                b=b-k;
                if(b<0)
                {
                    break;
                }
                else{
                    j++;
                    i=i+(k-1);

                }
            }
            cout<<d+f+j<<endl;
            c=0;j=0;d=0;
        }
    }
